language: node_js
node_js:
    - "10"
dist: xenial
sudo: false

branches:
    only:
        - master

cache:
    yarn: true
    directories:
        - node_modules

script:
    - yarn install
    - yarn build --base-href /example.angular-material.ts/ --prod --aot
    - cp dist/index.html dist/404.html

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
        branch: master
